<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="chassis_length" value="1.35" />
    <xacro:property name="chassis_width" value="0.5" />
    <xacro:property name="chassis_height" value="0.01" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.1778" />
    <xacro:property name="wheel_thickness" value="0.07" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.2135" />
    <xacro:property name="wheel_offset_y" value="0.285" />
    <xacro:property name="wheel_offset_z" value="0.01" />
    <xacro:property name="caster_wheel_radius" value="0.1778"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="1.1365" />

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${caster_wheel_offset_x-0.1} 0 0.075" rpy="0 0 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>


    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>



    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>

        <sensor name="camera" type="depth">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>B8G8R8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
                <min_depth>0.1</min_depth>
                <max_depth>100</max_depth>
            </plugin>
        </sensor>
    </gazebo>

</robot>